# Generated by Django 2.2.7 on 2020-04-19 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Covid',
            fields=[
                ('patient_number', models.AutoField(primary_key=True, serialize=False)),
                ('age', models.CharField(blank=True, max_length=10, null=True)),
                ('backup_notes', models.TextField(blank=True, null=True)),
                ('current_status', models.CharField(blank=True, max_length=50, null=True)),
                ('date_announced', models.TextField(blank=True, max_length=50, null=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('district', models.CharField(blank=True, max_length=50, null=True)),
                ('state', models.CharField(blank=True, max_length=50, null=True)),
                ('gender', models.CharField(blank=True, max_length=1, null=True)),
                ('nationality', models.CharField(blank=True, max_length=50, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('source1', models.URLField(blank=True, max_length=500, null=True)),
                ('source2', models.URLField(blank=True, max_length=500, null=True)),
                ('source3', models.URLField(blank=True, max_length=500, null=True)),
                ('statecode', models.CharField(blank=True, max_length=5, null=True)),
                ('status_change_date', models.TextField(blank=True, max_length=50, null=True)),
                ('type_of_transmission', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
