# Generated by Django 2.2.7 on 2020-04-16 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='covid',
            name='age',
            field=models.CharField(blank=True, default='', max_length=10, null=True),
        ),
    ]
